export { default as Home } from './Home'
export { default as Research } from './Research'
export { default as Blog } from './Blog'
export { default as Team } from './Team'
export { default as Contact } from './Contact'